jobs:
- template: build-templates/build-package.job.yml
  parameters:
    name: Windows
    vmImage: 'windows-latest'
    publishBuildArtifacts: 'true'
    publishCodeCoverage: 'true'
    
- template: build-templates/build-package.job.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu-latest'
    publishBuildArtifacts: 'false'
    publishCodeCoverage: 'false'

- template: build-templates/build-package.job.yml
  parameters:
    name: MacOS
    vmImage: 'macOS-latest'
    publishBuildArtifacts: 'false'
    publishCodeCoverage: 'false'